services:
  mxuserbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MXUserbot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - mxu_data:/app/mxu.rocksdb

volumes:
  mxu_data:
