services:
  mxuserbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MXUserbot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./persistent_data/mxu.rocksdb:/app/mxu.rocksdb:rw
      - ./persistent_data/community:/app/src/mxuserbot/community:rw
      - ./persistent_data/data:/app/data:rw
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=0,gid=0,mode=1777
      - /run:uid=0,gid=0,mode=1777
